owner: constructions-incongrues
repo: status

sites:
  - name: Da ! Heard It Records
    url: https://daheardit-records.net/fr/
  - name: Da ! Heard It Records (api)
    url: https://api.daheardit-records.net/
    expectedStatusCodes:
      - 403
  - name: Pastis Hosting
    url: https://www.pastis-hosting.net

assignees:
  - trivoallan

status-website:
  cname: status.constructions-incongrues.net
  name: Constructions Incongrues
  theme: light
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Pastis Hosting
      href: https://status.pastis-hosting.net
