owner: constructions-incongrues
repo: status

sites:
  # daheardit-records.net
  - name: Da ! Heard It Records - home
    url: https://daheardit-records.net/fr/
  - name: Da ! Heard It Records  - api
    url: https://api.daheardit-records.net/
    expectedStatusCodes:
      - 403

  # incongru.org
  - name: URL Info
    url: https://urlinfo.incongru.org/

  # mazemod.org
  - name: Mazemod
    url: https://www.mazemod.org/

  # musiqueapproximative.net
  - name: Musique Approximative
    url: https://www.musiqueapproximative.net/
  - name: Radio Approximative
    url: https://radio.musiqueapproximative.net/
  - name: Quickos Chante Noël
    url: https://quickoschantenoel.musiqueapproximative.net/

  # musiques-incongrues.net
  - name: Musiques Incongrues
    url: https://www.musiques-incongrues.net/forum/

  # ouiedire.net
  - name: Ouïedire
    url: https://www.ouiedire.net/

  # pardon-my-french.fr
  - name: Pardon My French
    url: https://www.pardon-my-french.fr/

  # pastis-hosting.net
  - name: Pastis Hosting
    url: https://www.pastis-hosting.net/

  # thebrainradio.com
  - name: The Brain
    url: https://www.thebrainradio.com/

  # thisisradioclash.org
  - name: This Is Radioclash
    url: https://www.thisisradioclash.org/

assignees:
  - trivoallan

status-website:
  cname: status.constructions-incongrues.net
  name: Constructions Incongrues
  theme: light
  navbar:
    - title: Constructions Incongrues
      href: /
