owner: constructions-incongrues
repo: status

sites:
  - name: daheardit-records.net
    url: https://www.daheardit-records.net
  - name: discutons.incongru.org
    url: https://discutons.incongru.org
  - name: legrandcahier.incongru.org
    url: https://legrandcahier.incongru.org
  - name: musiques-incongrues.net
    url: https://www.musiques-incongrues.net/forum/
  - name: musiqueapproximative.net
    url: https://www.musiqueapproximative.net
  - name: ouiedire.net
    url: https://www.ouiedire.net
  - name: nulsidecouvert.org
    url: https://nulsidecouvert.org

assignees:
  - trivoallan

status-website:
  cname: status.constructions-incongrues.net
  name: Constructions Incongrues
