owner: constructions-incongrues
repo: status

sites:
  - name: Da ! Heard It Records
    url: https://www.daheardit-records.net
  - name: Discutons
    url: https://discutons.incongru.org
  - name: Le Grand Cahier
    url: https://legrandcahier.incongru.org
  - name: Musiques Incongrues
    url: https://www.musiques-incongrues.net/forum/
  - name: Musique Approximative
    url: https://www.musiqueapproximative.net
  - name: Ouïedire
    url: https://www.ouiedire.net
  - name: Nul Si Découvert
    url: https://nulsidecouvert.org

assignees:
  - trivoallan

status-website:
  cname: status.constructions-incongrues.net
  name: Constructions Incongrues
