owner: constructions-incongrues
repo: status

sites:
  - name: Da ! Heard It Records
    url: https://daheardit-records.net/fr/
  - name: Musiques Incongrues
    url: https://www.musiques-incongrues.net/forum/
  - name: Pastis Hosting
    url: https://www.pastis-hosting.net

assignees:
  - trivoallan

status-website:
  cname: status.constructions-incongrues.net
  name: Constructions Incongrues
