owner: constructions-incongrues
repo: status

sites:
  # daheardit-records.net
  - name: Da ! Heard It Records - home
    url: https://daheardit-records.net/fr/
  - name: Da ! Heard It Records  - api
    url: https://api.daheardit-records.net/
    expectedStatusCodes:
      - 403

  # incongru.org
  - name: urlinfo
    url: https://urlinfo.incongru.org/

  # musiqueapproximative.net
  - name: Musique Approximative
    url: https://www.musiqueapproximative.net/
  - name: Radio Approximative
    url: https://radio.musiqueapproximative.net/
  - name: Quickos Chante Noël
    url: https://quickoschantenoel.musiqueapproximative.net/

  # musiques-incongrues.net
  - name: Musiques Incongrues
    url: https://www.musiques-incongrues.net/forum/

  # pastis-hosting.net
  - name: Pastis Hosting - home
    url: https://www.pastis-hosting.net/

assignees:
  - trivoallan

status-website:
  cname: status.constructions-incongrues.net
  name: Constructions Incongrues
  theme: light
