owner: constructions-incongrues
repo: status

sites:
  # daheardit-records.net
  - name: Da ! Heard It Records - home
    url: https://daheardit-records.net/fr/
  - name: Da ! Heard It Records  - api
    url: https://api.daheardit-records.net/
    expectedStatusCodes:
      - 403

  # incongru.org
  - name: Discutons
    url: https://discutons.incongru.org
  - name: Empilements
    url: https://empilements.incongru.org
  - name: Hypercriture
    url: https://hypercriture.incongru.org/
  - name: Le Grand Cahier
    url: https://legrandcahier.incongru.org
  - name: URL Info
    url: https://urlinfo.incongru.org

  # mazemod.org
  - name: Mazemod
    url: https://www.mazemod.org

  # millemilliards.net
  - name: Mille Milliards - Identités
    url: https://www.millemilliards.net/identites/
  - name: Mille Milliards - Tirages Ingrats
    url: https://tiragesingrats.millemilliards.net/
    maxResponseTime: 30000

  # musiqueapproximative.net
  - name: Musique Approximative
    url: https://www.musiqueapproximative.net/
  - name: Musique Approximative - Radio
    url: https://radio.musiqueapproximative.net

  # musiques-incongrues.net
  - name: Musiques Incongrues
    url: https://www.musiques-incongrues.net/forum/

  # ouiedire.net
  - name: Ouïedire
    url: https://www.ouiedire.net/

  # pardon-my-french.fr
  - name: Pardon My French
    url: https://www.pardon-my-french.fr/

  # partouze-cagoule.fr
  - name: Partouze Cagoule
    url: https://www.partouze-cagoule.fr/
  - name: Signé Sexe
    url: https://signesexe.partouze-cagoule.fr/
  - name: Kneeporn
    url: https://kneeporn.partouze-cagoule.fr/
  - name: Rosebud
    url: https://rosebud.partouze-cagoule.fr/

  # pastis-hosting.net
  - name: Pastis Hosting
    url: https://www.pastis-hosting.net/

  # resterdigne.net
  - name: Coller
    url: https://coller.resterdigne.net
  - name: Faire Caca 2017
    url: https://fairecaca2017.resterdigne.net
  - name: La Grande Purge
    url: https://lagrandepurge.resterdigne.net
  
  # ruedesgardes.org
  - name: Aire de Jeux
    url: https://airedejeux.ruedesgardes.org
  - name: Pouézie
    url: https://pouezie.ruedesgardes.org

  # thebrainradio.com
  - name: The Brain
    url: https://www.thebrainradio.com/

  # thisisradioclash.org
  - name: This Is Radioclash
    url: https://www.thisisradioclash.org/

assignees:
  - trivoallan

status-website:
  cname: status.constructions-incongrues.net
  name: Constructions Incongrues
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  theme: dark
  navbar:
    - title: Interzone
      href: https://status.interzone.network
    - title: Jean-Cloude
      href: https://status.jeancloude.club
    - title: Pantagruweb
      href: https://status.pantagruweb.club
    - title: Pastis
      href: https://pastis-hosting.net

# - name: parishq.net
#     url: https://www.parishq.net
#   - name: partouze-cagoule
#     url: https://www.partouze-cagoule.fr
#   - name: pastis-hosting
#     url: https://www.pastis-hosting
#   - name: resterdigne.net
#     url: https://www.resterdigne.net
#   - name: ruedesgardes.org
#     url: https://www.ruedesgardes.org
